name: Build & Release PySide6 App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  pc-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
        # with:
        #   enable-cache: true
        
      - name: Set up Python versions
        run: uv python install
    
      - name: Install dependencies
        run: uv sync --locked --group build

      - name: Create output directory
        run: mkdir dist_out/
        
      - name: Build binary with pyside6-deploy
        run: uv run pyside6-deploy -v -c pysidedeploy.spec

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist_out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
